version: 2

updates:

  # Update npm packages
  - package-ecosystem: npm
    directory: /
    reviewers:
      - alphagov/design-system-developers
    schedule:
      # Defaults to weekly on Monday
      interval: weekly
      time: "10:30"
      # Setting a timezone so we let dependabot worry about BST
      timezone: "Europe/London"
    versioning-strategy: increase

    allow:
      - dependency-type: direct

  # Update Ruby gems
  - package-ecosystem: bundler
    directory: /
    reviewers:
      - alphagov/design-system-developers
    schedule:
      # Defaults to weekly on Monday
      interval: weekly
      time: "10:30"
      # Setting a timezone so we let dependabot worry about BST
      timezone: "Europe/London"
    versioning-strategy: increase

    allow:
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - alphagov/design-system-developers
    schedule:
      # Defaults to weekly on Monday
      interval: weekly
      time: "10:30"
      # Setting a timezone so we let dependabot worry about BST
      timezone: "Europe/London"
