version: 2

updates:

  # Update npm packages
  - package-ecosystem: npm
    directory: /
    reviewers:
      - alphagov/design-system-developers
    schedule:
      interval: daily
    allow:
      - dependency-type: all

