version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 15

    # Group packages into shared PR
    groups:
      # First in list so Dependabot looks at updating those first
      design-system:
        patterns:
          - "govuk-frontend"
          - "accessible-autocomplete"
    schedule:
      interval: monthly
      time: "10:30"
      timezone: "Europe/London"
    versioning-strategy: increase

    allow:
      - dependency-type: direct

  # Update Ruby gems
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
      time: "10:30"
      timezone: "Europe/London"
    versioning-strategy: increase

    allow:
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "10:30"
      timezone: "Europe/London"
