inherit_gem:
  rubocop-govuk:
    - config/default.yml

# Exclude `/vendor` because on Travis other gems get installed there
# Not a problem locally as gems get installed globally outside project 
AllCops:
  Exclude:
    - './vendor/**/*'

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
