language: ruby
# Use Ruby 2.6 to avoid requiring the installed bundler version to exactly
# match the version in Gemfile.lock, as seen in the version of RubyGems that
# shipped with Ruby 2.5.
dist: bionic
cache: bundler
script:
  - bundle exec middleman build
  - bundle exec rake
  - npm run check-links

env:
  global:
  # CloudFoundry credentials for deployment
  - CF_API="https://api.cloud.service.gov.uk"
  - CF_ORG="govuk-design-system"
  - CF_SPACE="frontend-docs"
  - CF_USERNAME="design-system-deploy+frontend-docs@digital.cabinet-office.gov.uk"
  # CF_PASSWORD
  - secure: "pn2phUSd6A6NRQzOyRT11yQOlYQCD1qLbwFQbaIqOugstKF2aFqgDJEWA/wTkZgnyTRPd4r3DiBb1CsFUKbr053CfRv/PAEbD8kpAv2o3PdWUKdiefFmbSP14rkYouSJApG538wqZElh1x+ehRVbUF1KmqDCYHf7dOnlak0Qe2ClRhR7X8d0/TjWV32wnXbLfN1f9VF4su6mYz4ot87XRBMPCdKC8lF6vW4RKhMgu9nUUWGe/M2cdCEqu0UP673Y+0+b14XjqAfNn+BLcgfhhb9ROnHRqVOxOsgZJY3SmRVKFpH4FwsTM01vS97FoqmhuFzMcFn4ldzPd1ZdHgDjYTxucB830uYqI2TJk/aVdaS6C/kD5uwa9gPhnQGyJSHffr93A3Xygqww17YfRXrtSzV9kEHSiRV6U9fmX1mb/l2PEifLAiDf4qdTaqSwTYT7NptJY9AhSKcsRPkZQGuOezcfunKtg6zTl1nkTBebeJdz8m0zdp3heafrfXaKwpU9s/3UfDHTlsqSiI1OhWRMOEVWn6NE0Q0p6vxh+sl9Mg3zaYLcDFx/MuiZ/8TLA2QZBsRtn+0RUNKsx4F2/AHcj6m9P0eMXNMGe5tGRdDDr6j0RuPmh0vedKB8fgw9V+KjWEVPHSd3on4veAT8JS1GMJDqqIHyo+Tdk2gA0lcf2FM="

# Install CloudFoundry CLI tools
before_deploy:
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install -y cf7-cli

before_script:
  - npm install

# We use a script rather than using Travis' built in CloudFoundry provider
# because it does not support zero downtime deploys
# (https://github.com/travis-ci/dpl/pull/610)
deploy:
  provider: script
  script: "./bin/deploy-travis"
  # We build the site as part of the build, so we want to keep it so it can be
  # deployed!
  skip_cleanup: true
  on:
    branch: main
